version: "3" 

services:
  angular:
    build: frontend 
    ports:
      - "4000:4000" 
    environment:
      - NODE_ENV=dev

  express: 
    build: api 
    ports:
      - "3000:3000"
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
  nginx: #name of the second service
    build: loadbalancer # specify the directory of the Dockerfile
    ports:
      - "80:8000" #specify ports forewarding
    links:
      - express
      - angular
