version: "3" 

services:
  angular:
    container_name:  frontend
    build: frontend 
    ports:
      - "4000:4000" 
    environment:
      - NODE_ENV=dev

  express: 
    container_name:  api
    build: api 
    ports:
      - "3000:3000"
    links:
      - database

  database: #
    container_name: database
    image: mongo 
    ports:
      - "27017:27017" 

  nginx: 
    build: loadbalancer 
    ports:
      - "80:8000" 
    links:
      - express
      - angular
